### ISSUE TITLE
Not working with boot2docker in windows

### ISSUE THREAD

**Issue by zivni** [neo4j-contrib/docker-neo4j#4]
When I run it exists after few seconds.

This is the output from the interactive shell:

>ln: failed to create symbolic link \`/data/graph.db/rrd': Protocol error
cp: cannot stat `/conf/*': No such file or directory
Starting Neo4j Server console-mode...
Using additional JVM arguments:  -server -XX:+DisableExplicitGC -Dorg.neo4j.server.properties=conf/neo4j-server.properties-Djava.util.logging.config.file=conf/logging.properties -Dlog4j.configuration=file:conf/log4j.properties -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled-XX:-OmitStackTraceInFastThrow -XX:hashCode=5 -Dneo4j.ext.udc.source=tarball -Djava.rmi.server.hostname=f8597329741d
2015-08-05 15:25:26.009+0000 INFO  [API] Setting startup timeout to: 120000ms based on 120000
2015-08-05 15:25:29.163+0000 INFO  [API] Successfully started database
2015-08-05 15:25:29.233+0000 INFO  [API] Successfully shutdown Neo4j Server.
2015-08-05 15:25:29.382+0000 INFO  [API] Successfully stopped database

**Comment by ryguyrg** [comment]
Thanks @zivni.  Can you see if the solutions suggested here work out for you?
http://serverfault.com/questions/476610/virtualbox-issue-with-symlinks-in-shared-folders

Looks like the user starting the VirtualBox needs to be an administrator, or you need to grant specific permissions in order for a symbolic link to be created on the host filesystem.

**Comment by zivni** [comment]
Thanks @ryguyrg. running as admin did the trick.
What I did is opened windows CMD with admin rights (run as administrator) and then ran boot2docker.

**Comment by benbc** [comment]
Hello @zivni. It sounds like your problem was fixed, so I'm going to close this issue. Please reopen it if that's not right.
